# Generated by Django 3.0.2 on 2021-04-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='liked',
            field=models.CharField(blank=True, choices=[('Liked', 'Liked'), ('Disliked', 'Disliked')], max_length=10),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='topic',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Health', 'Health'), ('Sport', 'Sport'), ('Tech', 'Tech')], default='Tech', max_length=50),
        ),
        migrations.AddField(
            model_name='postmessage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('liked', models.CharField(blank=True, choices=[('Like', 'Like'), ('Disliked', 'Disliked')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.PostMessage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
