# Generated by Django 3.0.2 on 2021-04-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210418_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmessage',
            name='user',
        ),
    ]
