# Generated by Django 3.0.2 on 2021-04-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_postmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='user',
        ),
    ]
