# Generated by Django 3.0.2 on 2021-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210418_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmessage',
            name='liked',
        ),
    ]
