# Generated by Django 3.0.2 on 2021-04-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_postmessage_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmessage',
            name='expiry',
            field=models.DurationField(null=True),
        ),
    ]
